# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de25fc982eac285585c4052f8dc680a5b16caa5d3682c5edfb8bbd4521055ee69a9742fc9dca0871492b2e752508df8654760e453d1d0b69242019a5fe31d4d5

test:
  secret_key_base: c3f826a12cdc6e476871e18e10034ae2bc989e824255088ce948dab76304a5c9ee6414f79b5976570e0fa184658f655da8a48cb5b485242584d38965b7d7db04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
